env:
  - distro: debianjessie
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml
  - distro: ubuntutrusty
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml
  - distro: ubuntuxenial
    init: "/sbin/init"
    run_opts: ""
    playbook: test.yml

services:
  - docker

before_install:
  - docker pull jebovic/${distro}-ansible:latest

script:
  # run container
  - container_id=$(mktemp)
  - docker run --detach --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 -p 443:443 -p 8888:8888 --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} jebovic/${distro}-ansible:latest "${init}" > "${container_id}"
  # syntax checking
  - docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} --syntax-check
  # test role
  - docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook}
  # test role idempotence
  - idempotence=$(mktemp)
  - docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/${playbook} | tee -a ${idempotence}
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  # test role tasks
  - docker exec "$(cat ${container_id})" ufw version
  - docker exec "$(cat ${container_id})" ufw status verbose
  - docker exec "$(cat ${container_id})" ufw app list

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: J01ezEK6MFSeEl82ZgqaT1vMTWXEb0VsxusI9fTET8K0my7GSa7F5+5jAnliowpJqQzPSpmqSBdql78ULDVPFoE6DEgEvaTpdH9X+DW6ZIyvTjD2XybJVxUPptIkdGrVzEm1XhR3rpCEdTbCRGHVu0CGtGrRtiG/f02xuvKCZaCC41DCpR3F3GxaFIKICmh+fc9b6v2yOl1LDuk5BUf39bzB4p+D3Fc1NcWibs4NAORaqjxdIvT1TYiHqI7dTBXwMEKYnwVi0AG205Bpz5/NFbAQ6dtTz3MZhDx0hQpj32ThXXGmWburCyCM357OYKCkeLAIsU3e/Wm0caJ+pT2n1VE5D/d+Sv8eTGKNlUYZtO49ibXHbYVjgzpRrZQxH00VXfUWAxe2p9eCcdyDKDZxql70hGC86LsJbvxcz+tkVWLOCSsLA72LRV30/AI4so5DDJIy+Cu9ESYMyCacCirJp+1dMfVmj9f4B8UZOG1I7ytpqB5aoG2IhHjRAoZQ+5URD+g4teipMvGZtUhKUTkRP32D07XGoLQx1T9fbzQ8zXLdTQyCRd2NvKjLtFYpFO/hlarfUg+LpOk+SDUzokZ/FSUC1u5zCaF3MqJF/T6xPIb7HegQreDjS3VXXv5EQ/PCoJ7tE+1m6nXYNH4OhZyiaYMejtMoS0HcXSRkqfJ3Ea8=
