---

- name: install packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: no
    update_cache:       yes
    cache_valid_time:   86400
  with_items: "{{ ufw_packages }}"

- name: reset firewall
  ufw:
    state: reset
  when: ufw_reset
  tags: ufw_reset

- include: config.yml
  tags: ufw_config

- name: start firewall
  ufw:
    state: "{{ ufw_state }}"
    logging: "{{ ufw_logging }}"
